Reporting Ad Impression for Banner and  Interstitial.
InMobi/googleads-mobile-ios-mediation pull request #7
Opened 2022-09-06 11:19 UTC by dineshgupthabavirisetti

2022-09-08 09:31 UTC, kshtgarg21 requested changes
GADMAdapterInMobiDelegateManager *delegateManager =
      GADMAdapterInMobiDelegateManager.sharedInstance;
  [delegateManager removeDelegateForPlacementIdentifier:_placementIdentifier];
  check if needed for banner or int?

2022-09-08 09:31 UTC, kshtgarg21 commented on adapters/InMobi/InMobiAdapter/GADMAdapterInMobiBannerAd.m
> +- (void)stopBeingDelegate {
remove

2022-09-08 09:31 UTC, kshtgarg21 commented on adapters/InMobi/InMobiAdapter/GADMAdapterInMobiInterstitialAd.m
> +}
remove both

2022-09-08 09:31 UTC, kshtgarg21 commented on adapters/InMobi/InMobiAdapter/GADMAdapterInMobiInterstitialAd.m
> +    _interstitialRenderCompletionHandler(nil,error);
fail callback missing

2022-09-08 11:39 UTC, dineshgupthabavirisetti commented on adapters/InMobi/InMobiAdapter/GADMAdapterInMobiBannerAd.m
> +- (void)stopBeingDelegate {
removed

2022-09-08 11:39 UTC, dineshgupthabavirisetti commented on adapters/InMobi/InMobiAdapter/GADMAdapterInMobiInterstitialAd.m
> +}
removed

2022-09-09 04:59 UTC, kshtgarg21 requested changes

2022-09-09 05:05 UTC, kshtgarg21 requested changes

2022-09-09 05:05 UTC, kshtgarg21 commented on adapters/InMobi/InMobiAdapter/GADMAdapterInMobiRewardedAd.m
> +        IMRequestStatus *error = [[IMRequestStatus alloc] initWithDomain:@"com.inmobi.ads.requeststatus" code:kIMStatusCodeInternalError userInfo:@{NSLocalizedDescriptionKey: @"Rewarded ad not ready
use nserror or use gam's error

2022-09-09 07:13 UTC, dineshgupthabavirisetti commented on adapters/InMobi/InMobiAdapter/GADMAdapterInMobiUtils.m
> +        NSDateComponents *components = [NSCalendar.currentCalendar
No way to fetch it in Configuration flow. In Connector flow also these fields got depicted and no replacement available.

2022-09-09 07:15 UTC, dineshgupthabavirisetti commented on adapters/InMobi/InMobiAdapter/GADMAdapterInMobiRewardedAd.m
> +        IMRequestStatus *error = [[IMRequestStatus alloc] initWithDomain:@"com.inmobi.ads.requeststatus" code:kIMStatusCodeInternalError userInfo:@{NSLocalizedDescriptionKey: @"Rewarded ad not ready
Resolved

2022-09-09 08:45 UTC, kshtgarg21 approved these changes

2022-09-09 08:50 UTC, merged